name: OpenSSF Scorecard Analysis
on:
  branch_protection_rule:
  schedule:
    - cron: '0 3 * * 1'
  push:
    branches: [ "main" ]

permissions: read-all

jobs:
  analysis:
    name: OpenSSF Scorecard Analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write # Needed to upload the results to code scanning dashboard
      id-token: write # Needed to publish results to OpenSSF API and get a badge
    uses: fish-shop/workflows/.github/workflows/openssf-scorecard.yml@5f95f810f8716ed65452165bab6f3d89a606397e # v1.13.0
